create table test(
MEM_ID VARCHAR2(20),
MEM_PW VARCHAR2(20),
MEM_NAME VARCHAR2(20),
MEM_EMAIL VARCHAR2(20)
);

drop table test;
commit;
SELECT * FROM TEST;

INSERT INTO TEST VALUES('A','A','A','A');

select MEM_ID from TEST where MEM_NAME='HONG' AND MEM_EMAIL= 'HONG@NAVER.COM';
select MEM_ID from TEST WHERE MEM_NAME='HONG';